version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "iot-dynamo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14shvgaq0dr2c"
s3_prefix = "iot-dynamo-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
